version: 0.2
phases:
  install:
    commands:
      - echo "install phase....."
  pre_build:
    commands:
      - echo "pre build phase....."
  build:
    commands:
      - echo "build phase....."
      - instance_name="ZapTestInstance"
      - instance_id=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=${instance_name}" --query "Reservations[0].Instances[0].InstanceId" --output text --region ap-northeast-2)
      - aws ssm send-command --document-name "AWS-RunShellScript" --targets "Key=instanceids,Values=${instance_id}" --parameters "commands=['aws s3 cp s3://dast-hbucket/ZAP-build/target/webgoat-2023.6-SNAPSHOT.jar /home/ec2-user/webgoat-2023.6-SNAPSHOT.jar','aws s3 cp s3://dast-hbucket/report.py /home/ec2-user/report.py', 'aws s3 cp s3://dast-hbucket/install.py /home/ec2-user/install.py','python3 /home/ec2-user/install.py','sleep 50','java -jar webgoat-2023.6-SNAPSHOT.jar', 'sleep 50','python3 /home/ec2-user/report.py']" --region ap-northeast-2
      - sleep 100
      - aws s3 cp s3://dast-hbucket/Report/zap-scan-report.json /home/ec2-user/zap-scan-report.json
  post_build:
    commands:
      - risk_code_high=$(python -c "import json; data = json.load(open('/home/ec2-user/zap-scan-report.json')); print(sum(1 for item in data['site'][0]['alerts'] if item.get('riskcode') == '3'))")
      - if [ "$risk_code_high" -gt 0 ]; then
          echo "There are high alerts. Failing the build.";
        fi
      - echo "Build completed on $(date)"
