version: 0.2
phases:
  install:
    commands:
      - echo "install phase....."
  pre_build:
    commands:
      - echo "pre build phase....."
  build:
    commands:
      - echo "build phase....."
  post_build:
    commands:
      - aws ssm send-command --document-name "AWS-RunShellScript" --targets "Key=instanceids,Values=i-0594735cb2923b48d" --parameters "commands=['python3 /home/ec2-user/web_start.py', '/home/ec2-user/ZAP_2.14.0/zap.sh', '-cmd', '-quickurl', 'http://43.200.16.60:8080/WebGoat', '-quickout', '/home/ec2-user/zap-scan-report.json', 'python3 /home/ec2-user/report.py']" --region ap-northeast-2
      - echo "Build completed on $(date)"
      #- |
      #  aws lambda invoke \
      #    --function-name YourLambdaFunctionName \
      #    --invocation-type RequestResponse \
      #    --log-type Tail \
      #    s3://dast-hbucket/${report_filename}
